name: docs
on:
  push:
    branches:
      - main
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Install Build Tools
        run: |
          curl -sSL https://install.python-poetry.org | python
          echo $HOME/.poetry/bin >> $GITHUB_PATH
      - uses: actions/checkout@v4.0.0
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install Python Requirements
        run: |
          poetry install
      - name: Build Docs
        run: |
          poetry run sphinx-apidoc -H "API Reference" -o docs/api_reference recline
          poetry run sphinx-build -b html docs build/html
      - name: Publish Docs
        uses: JamesIves/github-pages-deploy-action@15de0f09300eea763baee31dff6c6184995c5f6a # v4.7.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build/html
